version: 3.8
services:
  #nginx service
  web:
    image: nginx:latest
    container_na,e: nginx
    ports:
    - “8080:80”
  volumes:
  - ./ nginx:/etc/nginx/conf.d
  - ./app:/var/www/html
  depends_on:
  - php
  networks:
  - app-network
#php-fpm service
php:
  image: php:7.4-fpm
  container_name: php-fmp
  volumes:
  - ./app:/var/www/html
  networks:
  - appnetwork
#mysql service
db:
  image: mysql:5.7
  container_name: mysql
  enviroment:
    MYSQL_ROOT_PASSWORK: root
    MYSQL_DATABASE: mydatabase
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  volumes:
  - db-data:/var/lib/mysql
  network:
  - app-network
networks:
  app-network:
    drive: bridge
volumes:
  db-data: null
