name: test
on: [push]
jobs:
   
    local-action:
        runs-on: ubuntu-latest

        env:
          MY_VAR: Mi variable de entorno

        steps:
          - name: Test
            env:
              STEP_MY_VAR: variable nivel step
            run: echo "Valor $STEP_MY_VAR"
          