name: Hola Mundo

# Hacer pull y request
#on:  [push, pull_request]


#para que haga pull y request en una rama en especifico
on:  
  push:
    branches: 
      - workflows
  pull_request:
    branches: 
      - workflows

jobs:
  hola:
    runs-on: ubuntu-latest
  
    steps:
      - name: Hola Mundo
        run: echo "hola, desde la rama workflows"
      
      
      - name: touch file
        run: touch hola.txt

      - name: Set test
        run:  echo "hola, hola nuevamente desde workflow" >> hola.txt  
  other:
    runs-on: ubuntu-latest
    needs: [hola]

    steps:  
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: LS
      run: ls -la