name: test1
on: [push]
jobs:
   
    local-action:
        runs-on: ubuntu-latest

        steps:
          - name: LS
            run: |
             mkdir ~/ssh
             echo "${{secrets.SSH_KEY}}" >> ~/ssh/id_rsa
             chmod 600  ~/ssh/id_rsa
             ssh-keyscan -h 127.0.1.1  >> ~/ssh/known:hosts
             cat ~/ssh/known:hosts